"""
export_claude_log.py -- regenerate the unedited Claude Code transcript(s).

Converts a Claude Code session JSONL into the transcript format used in this
directory (see README.md): every USER prompt and every ASSISTANT text
response, in order, verbatim. Excluded (they carry no conversational
content): tool calls, tool results, thinking blocks, system/harness
messages, injected reminders (<system-reminder>), local-command wrappers
(/compact etc.), and harness-generated session-continuation summaries.
Nothing kept is altered, shortened, or paraphrased.

Usage (re-run before submission so the transcript covers the full session):
    python ai_logs/export_claude_log.py <session.jsonl> <out.md>
"""
import json
import sys
from pathlib import Path

# A text block is dropped iff it IS harness output, i.e. it starts with one
# of these wrappers (block-level exclusion, never word-level editing).
HARNESS_PREFIXES = (
    "<system-reminder", "<local-command-", "<command-name>",
    "<command-message>", "<command-args>",
    "This session is being continued from a previous conversation",
    "Caveat: The messages below were generated by the user while running",
)


def text_blocks(message: dict) -> list:
    content = message.get("content")
    if isinstance(content, str):
        return [content]
    blocks = []
    if isinstance(content, list):
        for item in content:
            if isinstance(item, dict) and item.get("type") == "text":
                blocks.append(item.get("text", ""))
    return blocks


def keep(block: str) -> bool:
    t = block.strip()
    return bool(t) and not t.startswith(HARNESS_PREFIXES)


def export(jsonl_path: Path, out_path: Path) -> tuple:
    emissions = []  # (role, text) in file order
    with open(jsonl_path, encoding="utf-8") as fh:
        for line in fh:
            try:
                obj = json.loads(line)
            except json.JSONDecodeError:
                continue
            if obj.get("type") not in ("user", "assistant") or obj.get("isMeta"):
                continue
            msg = obj.get("message") or {}
            if msg.get("role") not in ("user", "assistant"):
                continue
            kept = [b for b in text_blocks(msg) if keep(b)]
            if kept:
                emissions.append((msg["role"], "\n\n".join(kept)))

    # merge consecutive same-role emissions into one conversational turn
    turns = []
    for role, text in emissions:
        if turns and turns[-1][0] == role:
            turns[-1][1].append(text)
        else:
            turns.append((role, [text]))

    with open(out_path, "w", encoding="utf-8", newline="\n") as out:
        for role, texts in turns:
            out.write(f"## {role.upper()}\n\n")
            out.write("\n\n".join(texts).strip() + "\n\n")

    n_user = sum(1 for r, _ in turns if r == "user")
    n_asst = sum(1 for r, _ in turns if r == "assistant")
    return n_user, n_asst


if __name__ == "__main__":
    src, dst = Path(sys.argv[1]), Path(sys.argv[2])
    n_user, n_asst = export(src, dst)
    print(f"wrote {dst}: {n_user} USER turns, {n_asst} ASSISTANT turns")
